updated the file wich changes

diff --git a/.github/workflows/react-app-ci.yml b/.github/workflows/react-app-ci.yml
--- a/.github/workflows/react-app-ci.yml
+++ b/.github/workflows/react-app-ci.yml
@@ -12,43 +12,34 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-        continue-on-error: false
 
       - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v2
+        uses: google-github-actions/setup-gcloud@v3
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           service_account_key: ${{ secrets.GCP_SA_KEY }}
-          continue-on-error: false
-
-      - name: Authenticate to Google Cloud
-        run: |
-          echo "Authenticating to Google Cloud..."
-          gcloud auth activate-service-account --key-file="${{ secrets.GCP_SA_KEY }}"
-          if [ $? -ne 0 ]; then
-            echo "Error: Google Cloud authentication failed."
-            exit 1
-          fi
-        continue-on-error: false
 
       - name: Create GCS directory
+        env:
+          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
+          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
         run: |
           VERSION=${GITHUB_REF#refs/tags/}
           echo "Creating GCS directory ${VERSION}..."
-          gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} gs://${{ secrets.GCP_BUCKET_NAME }}/${VERSION}
+          gsutil mb -p ${GCP_PROJECT_ID} gs://${GCP_BUCKET_NAME}/${VERSION} || true
           if [ $? -ne 0 ]; then
-            echo "Error: File upload to GCS failed."
+            echo "Error: Failed to create GCS directory."
             exit 1
           fi
-        continue-on-error: false
 
       - name: Upload files to GCS
+        env:
+          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
         run: |
-          echo "Uploding files to GCS...."
           VERSION=${GITHUB_REF#refs/tags/}
-          gsutil -m cp -r ./src/* gs://${{ secrets.GCP_BUCKET_NAME }}/${VERSION}/
+          echo "Uploading files to GCS..."
+          gsutil -m cp -r ./src/* gs://${GCP_BUCKET_NAME}/${VERSION}/
           if [ $? -ne 0 ]; then
             echo "Error: File upload to GCS failed."
             exit 1
           fi
-        continue-on-error: false
