updated the gcs version to 5

diff --git a/.github/workflows/react-app-ci.yml b/.github/workflows/react-app-ci.yml
--- a/.github/workflows/react-app-ci.yml
+++ b/.github/workflows/react-app-ci.yml
@@ -19,27 +19,27 @@ jobs:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           service_account_key: ${{ secrets.GCP_SA_KEY }}
 
-      # - name: Create GCS directory
-      #   env:
-      #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
-      #     GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
-      #   run: |
-      #     VERSION=${GITHUB_REF#refs/tags/}
-      #     echo "Creating GCS directory ${VERSION}..."
-      #     gsutil mb -p ${GCP_PROJECT_ID} gs://${GCP_BUCKET_NAME}/${VERSION}
-      #     if [ $? -ne 0 ]; then
-      #       echo "Error: Failed to create GCS directory."
-      #       exit 1
-      #     fi
-
-      - name: Upload files to GCS
+      - name: Create GCS directory
         env:
+          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
           GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
         run: |
           VERSION=${GITHUB_REF#refs/tags/}
-          echo "Uploading files to GCS...${VERSION}"
-          gsutil -m cp -r ./src/* gs://${GCP_BUCKET_NAME}/${VERSION}/
+          echo "Creating GCS directory ${VERSION}..."
+          gsutil mb -p ${GCP_PROJECT_ID} gs://${GCP_BUCKET_NAME}/${VERSION}
           if [ $? -ne 0 ]; then
-            echo "Error: File upload to GCS failed."
+            echo "Error: Failed to create GCS directory."
             exit 1
           fi
+
+      # - name: Upload files to GCS
+      #   env:
+      #     GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
+      #   run: |
+      #     VERSION=${GITHUB_REF#refs/tags/}
+      #     echo "Uploading files to GCS...${VERSION}"
+      #     gsutil -m cp -r ./src/* gs://${GCP_BUCKET_NAME}/${VERSION}/
+      #     if [ $? -ne 0 ]; then
+      #       echo "Error: File upload to GCS failed."
+      #       exit 1
+      #     fi
